# -*- coding: utf-8 -*-
"""datasetThaiNumCr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1whFX6WUdxfi3h62EivMcVgID5wdlAbAK
"""

!apt-get update
!apt-get install -y fonts-thai-tlwg fonts-leelawadee fonts-thai-scalable

import os, random, shutil, glob, numpy as np, matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont, ImageOps

# 1. Update and install standard Thai font packages
!apt-get update
!apt-get install -y fonts-thai-tlwg fonts-kacst fonts-liberation

# 2. Automatically find ALL available .ttf files in the system
# This is safer than hardcoding paths that might change
FONT_PATHS = glob.glob("/usr/share/fonts/truetype/**/*.ttf", recursive=True)
# Filter for Thai-specific fonts to keep it relevant
THAI_FONTS = [f for f in FONT_PATHS if any(x in f.lower() for x in ['thai', 'tlwg', 'garuda', 'loma', 'waree'])]

print(f"Total fonts found: {len(FONT_PATHS)}")
print(f"Thai-compatible fonts found: {len(THAI_FONTS)}")

if len(THAI_FONTS) == 0:
    # Fallback to any font if Thai-specific isn't found
    if len(FONT_PATHS) > 0:
        THAI_FONTS = FONT_PATHS
    else:
        raise Exception("No .ttf fonts found. Check apt-get installation.")

# Update your CLASSES and settings
CLASSES = ['๕๖', '๕๗', '๕๘', '๕๙', '๖๐']
DATA_DIR = 'dataset_thai_test'
NUM_SAMPLES_PER_CLASS = 2500

if os.path.exists(DATA_DIR): shutil.rmtree(DATA_DIR)
for c in CLASSES: os.makedirs(os.path.join(DATA_DIR, c), exist_ok=True)

import os, random, shutil, numpy as np, matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont, ImageOps

# 1. ติดตั้งฟอนต์
!apt-get install -y fonts-thai-tlwg fonts-sipa-arundhati

CLASSES = ['๕๖', '๕๗', '๕๘', '๕๙', '๖๐']
DATA_DIR = 'dataset_thai_test' # เปลี่ยนชื่อโฟลเดอร์เพื่อความสดใหม่
NUM_SAMPLES_PER_CLASS = 2500

FONT_PATHS = [
    "/usr/share/fonts/truetype/thai-tlwg/Loma.ttf",
    "/usr/share/fonts/truetype/thai-tlwg/Purisa.ttf",
    "/usr/share/fonts/truetype/thai-tlwg/Waree.ttf",
    "/usr/share/fonts/truetype/thai-tlwg/Kinnari.ttf",
    "/usr/share/fonts/truetype/thai-tlwg/Norasi.ttf"
]

if os.path.exists(DATA_DIR): shutil.rmtree(DATA_DIR)
for c in CLASSES: os.makedirs(os.path.join(DATA_DIR, c), exist_ok=True)

def create_final_image(text, save_path):
    # เริ่มด้วยภาพขนาดใหญ่ 56x56
    img = Image.new('L', (56, 56), color=0)
    draw = ImageDraw.Draw(img)

    f_path = random.choice(FONT_PATHS)

    # --- แก้ไขตรงนี้: ลดขนาดฟอนต์ลงเพื่อให้ตัวเลขมีพื้นที่ว่าง ไม่เบียดกัน ---
    # ขนาด 22-26 ในเฟรม 56 จะเท่ากับประมาณ 11-13 ในเฟรม 28 (ผอมลงชัดเจน)
    font_size = random.randint(22, 26)
    font = ImageFont.truetype(f_path, font_size)

    # จัดกึ่งกลาง
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    w, h = right - left, bottom - top

    # สุ่มตำแหน่งเบาๆ ไม่ให้กระเด็นติดขอบ
    x = (56 - w) // 2 + random.randint(-2, 2) # <<<<< conf
    y = (56 - h) // 2 + random.randint(-2, 2) # <<<<< conf

    draw.text((x, y), text, fill=255, font=font)

    # --- แก้ไขตรงนี้: ลดแรงหมุนลงเพื่อรักษาทรง "หาง" ของเลข ๖ และ ๗ ---
    img = img.rotate(random.randint(-10, 10)) # <<<<< conf

    # ย่อกลับมาที่ 28x28
    img = img.resize((28, 28), Image.LANCZOS) # ใช้ LANCZOS เพื่อให้เส้นเนียนขึ้น

    # เพิ่ม Noise เล็กน้อย (ปรับให้ Noise เบาลงเพื่อไม่ให้กวนหัวตัวเลข)
    img_array = np.array(img)
    if random.random() > 0.7: # ลดโอกาสเกิด noise
        noise = np.random.normal(0, 3, img_array.shape)
        img_array = np.clip(img_array.astype(float) + noise, 0, 255).astype('uint8')

    Image.fromarray(img_array).save(save_path)

print("กำลังสร้างชุดข้อมูลฉบับแก้ปัญหาเลข ๕๖...")
for text in CLASSES:
    print(f"กำลังสร้างคลาส {text}...")
    for i in range(NUM_SAMPLES_PER_CLASS):
        create_final_image(text, os.path.join(DATA_DIR, text, f"{text}_{i}.png"))

print("-" * 30)
print(f"สร้างข้อมูลเสร็จสิ้น! แนะนำให้รันการ Train ใหม่ (Re-train) ทั้งหมดครับ")

# แสดงตัวอย่างเพื่อเช็คว่าเลข ๕๖ มีช่องว่างตรงกลางไหม
plt.figure(figsize=(10, 2))
sample_56 = os.listdir(os.path.join(DATA_DIR, '๕๖'))[0]
img_sample = Image.open(os.path.join(DATA_DIR, '๕๖', sample_56))
plt.imshow(img_sample, cmap='gray')
plt.title("Example of Class ๕๖ (Should have gap)")
plt.show()

"""**DATASET HARD**"""

import os, random, shutil, glob, numpy as np, matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter, ImageEnhance

# ---------------------------------------------------------
# [CONFIG]: ส่วนการตั้งค่าพื้นฐาน
# ---------------------------------------------------------
CLASSES = ['๕๖', '๕๗', '๕๘', '๕๙', '๖๐']
DATA_DIR = 'dataset_thai_hard'
NUM_SAMPLES_PER_CLASS = 2500  # จำนวนภาพต่อคลาส

# 1. ติดตั้งฟอนต์ (รันเฉพาะใน Colab/Debian)
!apt-get update
!apt-get install -y fonts-thai-tlwg fonts-kacst fonts-liberation

# 2. ค้นหา Font ในเครื่องแบบอัตโนมัติ
all_fonts = glob.glob("/usr/share/fonts/truetype/**/*.ttf", recursive=True)
# คัดเฉพาะฟอนต์ไทย (ปรับเปลี่ยน Keyword ได้ถ้าต้องการฟอนต์เพิ่ม)
THAI_FONTS = [f for f in all_fonts if any(x in f.lower() for x in ['thai', 'tlwg', 'garuda', 'loma', 'waree'])]

if len(THAI_FONTS) == 0:
    THAI_FONTS = all_fonts # Fallback ถ้าหาฟอนต์ไทยไม่เจอจริงๆ
    print("Warning: No Thai fonts found, using system fonts.")

# เตรียมโฟลเดอร์
if os.path.exists(DATA_DIR): shutil.rmtree(DATA_DIR)
for c in CLASSES: os.makedirs(os.path.join(DATA_DIR, c), exist_ok=True)

# ---------------------------------------------------------
# [CONFIG]: ฟังก์ชันสร้างภาพ - ปรับความยากได้ที่นี่
# ---------------------------------------------------------
def create_final_image(text, save_path):
    # เริ่มต้นด้วย Canvas ขนาดใหญ่เพื่อให้บิดภาพได้เนียน (Supersampling)
    canvas_size = 64
    img = Image.new('L', (canvas_size, canvas_size), color=0)
    draw = ImageDraw.Draw(img)

    # เลือก Font สุ่ม
    f_path = random.choice(THAI_FONTS)

    # <<< CONFIG: ขนาดตัวอักษร (สัมพันธ์กับ canvas_size) >>>
    font_size = random.randint(26, 34)
    font = ImageFont.truetype(f_path, font_size)

    # คำนวณตำแหน่งกึ่งกลาง
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    w, h = right - left, bottom - top

    # <<< CONFIG: การเขย่าตำแหน่ง (Jitter) >>>
    # ปรับเลขใน randint เพื่อให้ตัวเลขไม่อยู่ตรงกลางเป๊ะ
    x = (canvas_size - w) // 2 + random.randint(-6, 6)
    y = (canvas_size - h) // 2 + random.randint(-6, 6)

    draw.text((x, y), text, fill=255, font=font)

    # --- ขั้นตอน Augmentation (ทำให้ยากขึ้น) ---

    # 1. <<< CONFIG: การหมุน (Rotation) >>>
    # ปรับองศาได้ (-45, 45 จะยากมาก)
    img = img.rotate(random.randint(-25, 25), resample=Image.BICUBIC)

    # 2. <<< CONFIG: การบิดภาพ (Affine/Perspective) >>>
    # ทำให้ภาพดูเหมือนถ่ายจากมุมเอียง
    if random.random() > 0.5:
        m = random.uniform(-0.2, 0.2) # แรงบิด
        img = img.transform((canvas_size, canvas_size), Image.AFFINE,
                            (1, m, 0, 0, 1, 0), Image.BICUBIC)

    # 3. <<< CONFIG: ความเบลอและความคม (Blur/Sharpness) >>>
    if random.random() > 0.7:
        # สุ่มเบลอ (เหมือนภาพหลุดโฟกัส)
        img = img.filter(ImageFilter.GaussianBlur(radius=random.uniform(0.5, 1.0)))
    elif random.random() > 0.7:
        # สุ่มเร่งความคม (ทำให้เส้นแตก)
        enhancer = ImageEnhance.Sharpness(img)
        img = enhancer.enhance(random.uniform(2.0, 4.0))

    # 4. ย่อขนาดลงเหลือ 28x28 สำหรับ Model
    img = img.resize((28, 28), Image.LANCZOS)

    # 5. <<< CONFIG: สัญญาณรบกวน (Noise) >>>
    img_array = np.array(img).astype(float)

    # Gaussian Noise (ความสว่างไม่คงที่)
    noise_strength = random.uniform(5, 15) # ยิ่งเลขเยอะ ยิ่งมีเม็ดทรายเยอะ
    img_array += np.random.normal(0, noise_strength, img_array.shape)

    # Salt & Pepper Noise (จุดขาวดำ)
    if random.random() > 0.8:
        prob = 0.02 # โอกาสเกิดจุด
        for i in range(img_array.shape[0]):
            for j in range(img_array.shape[1]):
                rdn = random.random()
                if rdn < prob: img_array[i][j] = 0
                elif rdn > (1-prob): img_array[i][j] = 255

    # ตัดส่วนเกินและบันทึก
    img_array = np.clip(img_array, 0, 255).astype('uint8')
    Image.fromarray(img_array).save(save_path)

# ---------------------------------------------------------
# ส่วนการรันโปรแกรม
# ---------------------------------------------------------
print(f"กำลังสร้างข้อมูล {NUM_SAMPLES_PER_CLASS * len(CLASSES)} ภาพ...")
for text in CLASSES:
    print(f"Generating class: {text}")
    for i in range(NUM_SAMPLES_PER_CLASS):
        create_final_image(text, os.path.join(DATA_DIR, text, f"{text}_{i}.png"))

print("-" * 30)
print("สร้าง Dataset เสร็จสมบูรณ์!")

# แสดงตัวอย่างความยาก 10 ภาพแรกของคลาส ๕๖
plt.figure(figsize=(15, 3))
files = os.listdir(os.path.join(DATA_DIR, '๕๖'))[:10]
for i, f in enumerate(files):
    img = Image.open(os.path.join(DATA_DIR, '๕๖', f))
    plt.subplot(1, 10, i+1)
    plt.imshow(img, cmap='gray')
    plt.axis('off')
plt.show()

"""# DELETE"""

import shutil
import os

# ระบุชื่อโฟลเดอร์ที่ต้องการลบ
target_dir = 'dataset_thai_test'

if os.path.exists(target_dir):
    shutil.rmtree(target_dir)
    print(f"ลบ {target_dir} เรียบร้อยแล้ว!")
else:
    print(f"ไม่พบโฟลเดอร์ {target_dir}")

"""# TRAIN MODEL"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 1. ตั้งค่าโฟลเดอร์ให้ตรงกับที่เราเพิ่งสร้างใหม่
DATA_DIR = 'dataset_thai_hard'

# 2. ปรับ Augmentation ให้ "สมดุล"
# ไม่ให้เลขบิดเบี้ยวจนหัวและตัวเลขมาทับกันเอง
datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,      # ลดลงเล็กน้อยเพื่อรักษาทรงเลข ๖ ไม่ให้เหมือน ๗
    width_shift_range=0.1,  # ลดลงเพื่อไม่ให้เลขหลุดขอบ
    height_shift_range=0.1,
    shear_range=0.2,        # การเอียงพอประมาณช่วยแยกหาง ๗ และ ๙
    zoom_range=0.1,         # ลดการซูมลงเพื่อไม่ให้ตัวเลขขยายจนเบียดกัน
    validation_split=0.2
)

train_gen = datagen.flow_from_directory(
    DATA_DIR,
    target_size=(28, 28),
    color_mode='grayscale',
    batch_size=32,
    class_mode='sparse',
    subset='training'
)

val_gen = datagen.flow_from_directory(
    DATA_DIR,
    target_size=(28, 28),
    color_mode='grayscale',
    batch_size=32,
    class_mode='sparse',
    subset='validation'
)

# 3. โครงสร้าง Model (ใช้ตัวที่คุณส่งมา ซึ่งถือว่ามีประสิทธิภาพสูงอยู่แล้ว)
model = models.Sequential([
    layers.Conv2D(32, (3, 3), padding='same', activation='relu', input_shape=(28, 28, 1)),
    layers.BatchNormalization(),
    layers.Conv2D(32, (3, 3), padding='same', activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(len(CLASSES), activation='softmax')
])

# 4. ใช้ Adam Optimizer พร้อมกับ Learning Rate ที่เหมาะสม
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# 5. เพิ่ม EarlyStopping (Optional) เพื่อหยุดเทรนถ้าแม่นยำที่สุดแล้ว
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# เริ่มต้นการเทรน
print("Starting training with fine-tuned dataset...")
history = model.fit(
    train_gen,
    epochs=30,
    validation_data=val_gen,
    callbacks=[early_stop]
)

model.save('thai_ultimate_model_v4.h5') #<<<< model file name
print("Model saved as thai_ultimate_model_v5.h5")

!pip install gradio -q
import gradio as gr, cv2, numpy as np

def classify_thai_final_v4(img):
    if img is None: return None

    # 1. จัดการ Input จาก Gradio (ตรวจสอบว่าเป็นภาพวาดหรือไม่)
    # Gradio เวอร์ชันใหม่มักจะให้มาเป็น dict ที่มี key 'composite' หรือ 'layers'
    if isinstance(img, dict):
        img = img['composite']

    # 2. แปลงเป็น Grayscale
    if len(img.shape) == 3:
        img = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # 3. ตรวจสอบสีพื้นหลัง (ต้องเป็นพื้นดำ ตัวเลขขาว)
    if np.mean(img) > 127:
        img = cv2.bitwise_not(img)

    # 4. กำจัด Noise และทำให้เส้นคมชัด
    _, img = cv2.threshold(img, 40, 255, cv2.THRESH_BINARY)

    # --- ใช้ Erode เพื่อหดเส้นให้ผอมลงเล็กน้อย ช่วยแยกเลข ๕ กับ ๖ ---
    kernel = np.ones((2,2), np.uint8)
    img = cv2.erode(img, kernel, iterations=1)

    # 5. เตรียมภาพเข้า Model
    img_resized = cv2.resize(img, (28, 28))
    img_input = img_resized.astype('float32') / 255.0
    img_input = np.expand_dims(img_input, axis=(0, -1))

    # 6. Predict (ใช้ชื่อโมเดลล่าสุดที่คุณเทรน)
    pred = model.predict(img_input, verbose=0)[0]

    return {CLASSES[i]: float(pred[i]) for i in range(len(CLASSES))}

# สร้าง UI ใหม่ (ตัด brush_radius ออกเพื่อแก้ TypeError)
demo = gr.Interface(
    fn=classify_thai_final_v4,
    inputs=gr.Sketchpad(
        label="วาด ๕๖, ๕๗, ๕๘, ๕๙, ๖๐",
        type="numpy"
    ),
    outputs=gr.Label(num_top_classes=5, label="ผลการวิเคราะห์"),
    title="Thai Handwriting Recognition V4",
    description="เน้นวาดตัวเลขให้มีช่องว่างระหว่างกัน และตวัดหางให้ชัดเจน"
)

demo.launch(share=True)

"""# TEST MODEL"""

import os
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

# --- 1. ตั้งค่าพื้นฐาน ---
DATA_DIR_V5 = 'dataset_thai_hard'
MODEL_PATH = 'thai_ultimate_model_v4.h5'
CLASSES = ['56', '57', '58', '59', '60']

# --- 2. ตรวจสอบความพร้อมของ Model ---
if not os.path.exists(MODEL_PATH):
    raise FileNotFoundError(f"ไม่พบไฟล์ Model: {MODEL_PATH}")

# โหลด Model โดยปิด compile ไว้ก่อนเพื่อมาตั้งค่าใหม่ให้ตรงกับ Data
model = tf.keras.models.load_model(MODEL_PATH, compile=False)

# Compile ใหม่เพื่อแก้ปัญหา ValueError และคำเตือนเรื่อง Metrics
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy', # ใช้ sparse ให้ตรงกับ class_mode='sparse'
    metrics=['accuracy']
)
print("Load and Compile Model สำเร็จ!")

# --- 3. เตรียมข้อมูล Test จาก v5 ---
# หมายเหตุ: ต้องมั่นใจว่ารันโค้ดสร้างโฟลเดอร์ dataset_thai_v5 มาก่อนหน้านี้แล้ว
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
    DATA_DIR_V5,
    target_size=(28, 28),
    color_mode='grayscale',
    batch_size=32,
    class_mode='sparse', # ใช้ sparse เพื่อป้องกันปัญหา Rank mismatch
    shuffle=False        # สำคัญมากสำหรับการทำ Confusion Matrix
)

# --- 4. ทดสอบความแม่นยำ (Evaluate) ---
print("\nกำลังทดสอบความแม่นยำบน Dataset ...")
loss, accuracy = model.evaluate(test_generator)
print(f"\n[RESULTS] Accuracy : {accuracy * 100:.2f}%")

# --- 5. เจาะลึกด้วย Confusion Matrix ---
# ทำการ Predict ข้อมูลทั้งหมดใน Test Set
Y_pred = model.predict(test_generator)
y_pred = np.argmax(Y_pred, axis=1) # แปลงจาก Probabilities เป็น Class Index
y_true = test_generator.classes    # ค่าจริงจากโฟลเดอร์

# สร้าง Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

# แสดงผลเป็นกราฟ Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=CLASSES, yticklabels=CLASSES)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix: Thai Numbers')
plt.show()

# แสดง Report รายละเอียดของแต่ละคลาส (Precision, Recall, F1)
print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=CLASSES))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc, roc_auc_score
from sklearn.preprocessing import label_binarize
from itertools import cycle

# --- 8. คำนวณ ROC และ AUC ---

# 1. แปลง Label จริงให้เป็นรูปแบบ Binary (One-Hot Encoding)
# เนื่องจากเรามี 5 คลาส (0, 1, 2, 3, 4)
y_true_bin = label_binarize(y_true, classes=[0, 1, 2, 3, 4])
n_classes = len(CLASSES)

# 2. คำนวณค่า FPR, TPR และ AUC ของแต่ละคลาส
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    # Y_pred คือค่า Probability ที่ได้จาก model.predict() ในขั้นตอนก่อนหน้า
    fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], Y_pred[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# 3. คำนวณ Micro-average ROC curve และ AUC (ภาพรวมทั้งโมเดล)
fpr["micro"], tpr["micro"], _ = roc_curve(y_true_bin.ravel(), Y_pred.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

# --- 9. วาดกราฟ ROC Curve ---

plt.figure(figsize=(10, 8))

# วาดเส้น Micro-average (เส้นประหนา)
plt.plot(fpr["micro"], tpr["micro"],
         label=f'Micro-average ROC (area = {roc_auc["micro"]:0.2f})',
         color='deeppink', linestyle=':', linewidth=4)

# วาดเส้นของแต่ละคลาส (56, 57, 58, 59, 60)
colors = cycle(['aqua', 'darkorange', 'cornflowerblue', 'red', 'green'])
for i, color in zip(range(n_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2,
             label=f'ROC of class {CLASSES[i]} (AUC = {roc_auc[i]:0.2f})')

# วาดเส้น Baseline (เดาสุ่ม)
plt.plot([0, 1], [0, 1], 'k--', lw=2)

plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate ')
plt.ylabel('True Positive Rate ')
plt.title('ROC Curve & AUC Score: Thai Numbers Identification', fontsize=16)
plt.legend(loc="lower right")
plt.grid(alpha=0.3)
plt.show()

# พิมพ์ค่า AUC สรุปอีกครั้ง
print(f"\n[SUMMARY] Overall AUC Score (Micro): {roc_auc['micro']:.4f}")
for i in range(n_classes):
    print(f"Class {CLASSES[i]} AUC: {roc_auc[i]:.4f}")

"""# --- คำสั่งสำหรับ Zip ไฟล์เผื่อต้องการโหลดลงเครื่อง (Optional) ---
# !zip -r dataset_thai_numbers.zip dataset_thai_numbers/
"""

!zip -r dataset_thai_hard.zip dataset_thai_hard/
